{% set name = "mpi4jax" %}
{% set version = "0.2.0" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/PhilipVinc/mpi4jax/archive/v{{ version }}.tar.gz
  sha256: 7a4c8b9fa94959ca17678a976e5cea5eccb4ba66104d44b07de724a442d40324

build:
  number: 0
  skip: true  # [win or py<37]
  script: "{{ PYTHON }} -m pip install --no-deps -vvv . "


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - {{ mpi }}
    - mpi4py >=3.0.1
    - cython >=0.21
  run:
    - python
    - numpy
    - jax
    - {{ mpi }}
    - mpi4py >=3.0.1

test:
  requires:
    - pytest
  files:
    - testfun.py

about:
  home: https://github.com/PhilipVinc/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'MPI support for jax'
  description: |
    mpi4jax permits to insert MPI operations inside of jit-compiled jax 
    functions, and to perform automatic differentiation through them.
  doc_url: https://github.com/PhilipVinc/mpi4jax
  dev_url: https://github.com/PhilipVinc/mpi4jax

extra:
  recipe-maintainers:
    - PhilipVinc
