{% set name = "mpi4jax" %}
{% set version = "0.3.10.post1" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eef577c6700b8a04b9e17ea9cb704f2bba0b16f7d4465527931e374b08605988

build:
  number: 0
  skip: true  # [win or py<37]
  script:
    - export MPI4JAX_BUILD_MPICC=mpicc  # [build_platform != target_platform]
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - python
    - pip
    - {{ mpi }}
    - mpi4py >=3.0.1
    - cython >=0.21
  run:
    - python
    - numpy
    - jax >=0.3
    - jaxlib
    - {{ mpi }}
    - mpi4py >=3.0.1

test:
  requires:
    - pytest
    - {{ mpi }}
    - openssh  # [linux]
  source_files:
    - tests
    - examples
    - pyproject.toml

about:
  home: https://github.com/mpi4jax/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: MPI support for JAX
  description: |
    Zero-copy MPI communication of JAX arrays, for turbo-charged HPC applications in Python ⚡
  doc_url: https://mpi4jax.readthedocs.io
  dev_url: https://github.com/mpi4jax/mpi4jax

extra:
  recipe-maintainers:
    - PhilipVinc
    - dionhaefner
