{% set name = "mpi4jax" %}
{% set version = "0.7.0.post1" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 583066f9d5ce9a29a0b57b099cd3f51b0fa6206696ad3c3b47ea99520846cf6e

build:
  number: 0
  skip: true  # [win or py<310]
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ mpi }}
  host:
    - python
    - pip
    - {{ mpi }}
    - mpi4py >=3.0.1
    - cython >=0.21
  run:
    - python
    - numpy
    - jax >=0.3.25
    - jaxlib >=0.3.25
    - {{ mpi }}
    - mpi4py >=3.0.1

test:
  requires:
    - pytest
    - {{ mpi }}
    - openssh  # [linux]
  source_files:
    - tests
    - examples
    - pyproject.toml

about:
  home: https://github.com/mpi4jax/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: MPI support for JAX
  description: |
    Zero-copy MPI communication of JAX arrays, for turbo-charged HPC applications in Python ⚡
  doc_url: https://mpi4jax.readthedocs.io
  dev_url: https://github.com/mpi4jax/mpi4jax

extra:
  recipe-maintainers:
    - PhilipVinc
    - dionhaefner
