{% set name = "mpi4jax" %}
{% set version = "0.2.7" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 653752a343a529d6521d9797e3889bfc0f14b52f2a7478ca371c2e0cfd7a5c36

build:
  number: 1
  skip: true  # [win or py<37]
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .


requirements:
  build:
    - {{ compiler('c') }}
    - setuptools >=45
    - setuptools-scm >=4
    - toml
  host:
    - python
    - pip
    - {{ mpi }}
    - mpi4py >=3.0.1
    - cython >=0.21
  run:
    - python
    - numpy
    - jax >=0.2
    - {{ mpi }}
    - mpi4py >=3.0.1

test:
  requires:
    - pytest
    - {{ mpi }}
    - openssh  # [linux]
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/PhilipVinc/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: MPI support for jax
  description: |
    mpi4jax permits to insert MPI operations inside of jit-compiled jax 
    functions, and to perform automatic differentiation through them.
  doc_url: https://github.com/PhilipVinc/mpi4jax
  dev_url: https://github.com/PhilipVinc/mpi4jax

extra:
  recipe-maintainers:
    - PhilipVinc
