{% set name = "mpi4jax" %}
{% set version = "0.9.0.post1" %}
{% set mpi = mpi or "mpich" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2534512445f2b53de1456ccc3850c745dd8bdfb78f1c79f757bb71c33e768cdf

build:
  number: 0
  skip: true  # [win or target_platform=="osx-64" or py<310]
  script:
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - {{ mpi }}
    - jax >=0.6.0,!=0.9.0                     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - {{ mpi }}
    - mpi4py >=3.0.1
    - nanobind >=2.0.0
    - jax >=0.6.0,!=0.9.0
  run:
    - python
    - numpy
    - jax >=0.6.0,!=0.9.0
    - jaxlib >=0.6.0,!=0.9.0
    - {{ mpi }}
    - mpi4py >=3.0.1

test:
  requires:
    - pytest
    - {{ mpi }}
    - openssh  # [linux]
  source_files:
    - tests
    - examples
    - pyproject.toml

about:
  home: https://github.com/mpi4jax/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: MPI support for JAX
  description: |
    Zero-copy MPI communication of JAX arrays, for turbo-charged HPC applications in Python ⚡
  doc_url: https://mpi4jax.readthedocs.io
  dev_url: https://github.com/mpi4jax/mpi4jax

extra:
  recipe-maintainers:
    - PhilipVinc
    - dionhaefner
