{% set name = "mpi4jax" %}
{% set version = "0.3.7" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c98140e555ddec46e646c440a4ae2eb3bf9b17aa50a2d82c357fee29a6fb8675

build:
  number: 0
  skip: true  # [win or py<37]
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - setuptools >=45
    - toml
  host:
    - python
    - pip
    - {{ mpi }}
    - mpi4py >=3.0.1
    - cython >=0.21
  run:
    - python
    - numpy
    - jax >=0.2
    - jaxlib
    - {{ mpi }}
    - mpi4py >=3.0.1

test:
  requires:
    - pytest
    - {{ mpi }}
    - openssh  # [linux]
    - tqdm
  source_files:
    - tests
    - examples
    - pyproject.toml

about:
  home: https://github.com/mpi4jax/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: MPI support for JAX
  description: |
    Zero-copy MPI communication of JAX arrays, for turbo-charged HPC applications in Python ⚡
  doc_url: https://mpi4jax.readthedocs.io
  dev_url: https://github.com/mpi4jax/mpi4jax

extra:
  recipe-maintainers:
    - PhilipVinc
    - dionhaefner
